version: "3.2"

services:
  cc:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.1-internal
    ports:
      - target: 8091 # CCE
      - target: 8092 # SPM      
    volumes: 
      - .:/src 
    environment:
      - SAG_AQUARIUS

  devoracle:
    image: daerepository03.eur.ad.sag:4443/ccdevops/oracle:11.1
    environment: 
      - ORACLE_ALLOW_REMOTE=true

  dev1:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.1-node

  init:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.1-client
    volumes: 
      - ./:/src 
      # - ./clients/docker.properties:/root/.sag/cc.properties          
    environment: 
      - CC_SERVER=cc
    command: 
      sagccant nodes -Dnodes=dev1
    depends_on: 
      - cc
      - dev1
